before:
  hooks:
    - make clean
    - sh -c "NEXT_PUBLIC_VERSION={{ .Version}} make build-admin"
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/hetty
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: hettysoft
      name: homebrew-tap
    folder: Formula
    homepage:  https://hetty.xyz
    description: An HTTP toolkit for security research.
    license: MIT
    commit_author:
      name: David Stotijn
      email: dstotijn@gmail.com
    test: |
      system "#{bin}/hetty -v"

snapcrafts:
  - publish: true
    summary: An HTTP toolkit for security research.
    description: |
      Hetty is an HTTP toolkit for security research. It aims to become an open
      source alternative to commercial software like Burp Suite Pro, with
      powerful features tailored to the needs of the infosec and bug bounty
      community.
    grade: stable
    confinement: strict
    license: MIT
    apps:
      hetty:
        command: hetty
        plugs: ["network", "network-bind"]

scoop:
  bucket:
    owner: hettysoft
    name: scoop-bucket
  commit_author:
    name: David Stotijn
    email: dstotijn@gmail.com
  homepage:  https://hetty.xyz
  description: An HTTP toolkit for security research.
  license: MIT

dockers:
  - extra_files:
    - go.mod
    - go.sum
    - pkg
    - cmd
    - admin
    image_templates:
    - "ghcr.io/dstotijn/hetty:{{ .Version }}"
    - "ghcr.io/dstotijn/hetty:{{ .Major }}"
    - "ghcr.io/dstotijn/hetty:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/dstotijn/hetty:latest"
    - "dstotijn/hetty:{{ .Version }}"
    - "dstotijn/hetty:{{ .Major }}"
    - "dstotijn/hetty:{{ .Major }}.{{ .Minor }}"
    - "dstotijn/hetty:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/dstotijn/hetty"
    - "--build-arg=HETTY_VERSION={{.Version}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"